language: node_js
node_js:
- '6'
addons:
  sauce_connect:
    username: "arve0"
  jwt:
    secure: 1zg7pl8mPmpO1Cstkt9ipQAeDvw28Y0eKVO1yn6AOndY2kUqwAdeLEXU5AGKhmq0p3pixiDySkrFhZhpkC7wJb3cZoZNZSXcJu9Zq0XPYd7t7DqQ3pyvviYU1bhFjRuqQXgQQQJJ81G6v9v/2e/Tcu6PJzhnvTRMh7EKFrsHBlC+V1TpMqTb8v6wvH6sT6ZjFshIGCCeDbxC6Sw1oB78bZfTRc2xYrcwPU38+O4N3vPbWg/6VZRQyuvyMQHj/gEmmkEtR5psx3803bJ/x+ijfTyI+9ckN1daKQwO+2l6glc3+QmU6HUPGibU3nHdBvH0Lciwx7qhsDpsZUjep0gNEiB9/AjhGjG8zrLRmECeHiIoqmG7ujhc7PGA06TwaBaPM/ZXIUtOb7DWzz1Z0XkldqTqoV5GDsiNoZcoyiLmDZoPr1VUZBc1v8gJlUY05C0YnFi3+E9D3Y67HQU367lts03thD6WD8NBDsOmIjIFYvw7qe59/9Rk93m5Zg8vwhVBwDQVVdHdxLJBvHsyFZqFm2LQYHK/X9gAr/7T4iCJEAho9S6RdgOMJlQq+JxuRtNRUF3jdF2JJ237WvTYipH8zG8WKNNsHVeTlMVgoMHZ78dgnAfL2Nm2AM8tAV3qvtAbDFI4dqkT2wSC4kosPH9mI3IimCKl8SrU18Szo4tbWnI=
